name: Markdown to PDF

on:
  push:
    tags:
      - safepkt-v*.*.*
    paths:
      - 'docs/30-latest-mvp-for-safepkt-smart-contract-verifier.md'
      - 'docs/img/**'

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

      - name: Set env
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ env.RELEASE_NAME }}


  publication:

    needs: release

    name: Make PDF from document in markdown format

    runs-on: ubuntu-latest

    steps:

      - name: Set env
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install packages
        run: sudo apt-get install bash curl jq make

      - uses: actions/checkout@v2

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/img
          image_import: ./img
          build_html: false

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          path: |
            ${{ github.workspace }}/pdfs/30-latest-mvp-for-safepkt-smart-contract-verifier.pdf

      - name: Publish documentation
        run: /bin/bash -c "source $GITHUB_WORKSPACE/.github/workflows/publication/publish-mvp-documentation.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ env.RELEASE_NAME }}
